/**
 * Tier B — the generated context block.
 *
 * Agents without a session-hook API still read *some* instructions file before
 * they start. So note-tree writes the same budgeted seed into that file, fenced
 * between markers, and rewrites it whenever notes change.
 *
 * Three properties this must never violate:
 *
 * 1. **Idempotent.** Writing twice produces the same bytes. The block is
 *    replaced in place, never appended twice.
 * 2. **Non-destructive.** Everything you wrote around the block survives, and
 *    removing note-tree restores the file byte-for-byte.
 * 3. **Private by default.** `AGENTS.md` usually gets committed, so global
 *    (personal, cross-project) notes stay out of it unless you opt in.
 */

import fs from 'node:fs';
import path from 'node:path';
import { renderSeed } from '../seed.mjs';
import { ensureDir, readTextSafe, atomicWrite, backupFile } from '../fsutil.mjs';

export const START = '<!-- note-tree:start -->';
export const END = '<!-- note-tree:end -->';

const NOTICE =
  'Generated by note-tree. Everything between these markers is overwritten — edit your notes, not this block.';

/** Find the fenced block, tolerating whatever spacing surrounds it. */
function locate(text) {
  const start = text.indexOf(START);
  if (start === -1) return null;
  const end = text.indexOf(END, start);
  if (end === -1) return null;
  return { start, end: end + END.length };
}

function buildBlock(seedText) {
  return [START, `<!-- ${NOTICE} -->`, '', seedText, END].join('\n');
}

/**
 * YAML frontmatter some tools require (Kiro's `inclusion: auto`, Cursor's
 * `alwaysApply`). Added only when the file doesn't already start with one.
 */
function withFrontmatter(text, frontmatter) {
  if (!frontmatter || /^---\r?\n/.test(text)) return text;
  const lines = Object.entries(frontmatter).map(([k, v]) => `${k}: ${v}`);
  return `---\n${lines.join('\n')}\n---\n\n${text}`;
}

/**
 * Write or refresh the block in `file`.
 *
 * @returns `{ file, status, chars }` — status is `created` | `updated` |
 *          `unchanged` | `skipped`
 */
export function writeContextFile(file, seedText, { frontmatter = null, backupsDir = null } = {}) {
  const existing = readTextSafe(file, null);
  const block = buildBlock(seedText);

  if (existing === null) {
    // A brand-new file: frontmatter first, then the block, and a trailing
    // newline so appending to it later stays clean.
    const contents = withFrontmatter(`${block}\n`, frontmatter);
    ensureDir(path.dirname(file));
    atomicWrite(file, contents);
    return { file, status: 'created', chars: contents.length };
  }

  const found = locate(existing);
  let next;
  if (found) {
    next = existing.slice(0, found.start) + block + existing.slice(found.end);
  } else {
    // Append, leaving the user's content untouched above it.
    const sep = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
    next = `${existing}${sep}${block}\n`;
  }
  next = withFrontmatter(next, frontmatter);

  if (next === existing) return { file, status: 'unchanged', chars: next.length };
  if (backupsDir && !found) backupFile(file, backupsDir); // only the first time we touch it
  atomicWrite(file, next);
  return { file, status: found ? 'updated' : 'created', chars: next.length };
}

/**
 * Remove the block, restoring the surrounding file.
 *
 * The seam is repaired surgically rather than by reformatting the whole file:
 * we only collapse the blank lines *we* introduced where the block used to sit,
 * so a file we appended to comes back byte-identical to what it was before.
 * A file that contained nothing but our block (plus frontmatter we added) is
 * deleted outright.
 */
export function removeContextFile(file) {
  const existing = readTextSafe(file, null);
  if (existing === null) return { file, status: 'absent' };
  const found = locate(existing);
  if (!found) return { file, status: 'absent' };

  const before = existing.slice(0, found.start).replace(/\n+$/, '');
  const after = existing.slice(found.end).replace(/^\n+/, '').replace(/\n+$/, '');

  let next = before && after ? `${before}\n\n${after}` : before || after;
  if (next) next += '\n';

  // Nothing left but frontmatter we wrote ourselves? Then the file was ours.
  if (!next.trim() || /^---\r?\n[\s\S]*?\r?\n---\s*$/.test(next.trim())) {
    try {
      fs.unlinkSync(file);
      return { file, status: 'deleted' };
    } catch {
      return { file, status: 'error' };
    }
  }
  atomicWrite(file, next);
  return { file, status: 'cleaned' };
}

/**
 * Refresh every context file configured for this project.
 *
 * Called after each note mutation, so tools with no session hook still see
 * current memory. Failures are swallowed — a read-only repo or a locked file
 * must never break a note that already saved.
 */
export function refreshAll(ctx, adapters, { force = false } = {}) {
  const cfg = ctx.cfg;
  if (!force && cfg.contextFile?.autoRefresh === false) return [];
  // A project folder that has been moved or deleted still has notes in the
  // store. Rebuilding its index is right; conjuring the folder back into
  // existence to hold an AGENTS.md is not.
  if (ctx.cwd && !fs.existsSync(ctx.cwd)) return [];

  const includeGlobal = cfg.contextFile?.includeGlobal === true;
  const seed = renderSeed(
    ctx.entries('project'),
    includeGlobal ? ctx.entries('global') : [],
    cfg,
    { project: ctx.slug, recall: 'note-tree show <id>', save: 'note-tree add "…" --kind gotcha' },
  );

  const results = [];
  for (const adapter of adapters) {
    const spec = adapter.contextFile;
    if (!spec || spec.fallbackOnly) continue;
    const file = path.isAbsolute(spec.file) ? spec.file : path.join(ctx.cwd, spec.file);
    try {
      results.push(
        seed
          ? {
              agent: adapter.id,
              ...writeContextFile(file, seed.text, {
                frontmatter: spec.frontmatter,
                backupsDir: cfg.paths.backups,
              }),
            }
          : { agent: adapter.id, ...removeContextFile(file) },
      );
    } catch (err) {
      results.push({ agent: adapter.id, file, status: 'error', error: err?.message });
    }
  }
  return results;
}
